### ISSUE TITLE
User can see their car

### ISSUE THREAD

**Issue by Yang-Darren** [Yang-Darren/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] Create new html page skeleton
- [x] Link CSS page
- [x] Add CSS
- [x] Style the car and remove unnevessary CSS
- [x] Test the functions in a private browser
- [x] Fix errors
