### ISSUE TITLE
User can turn their car

### ISSUE THREAD

**Issue by Yang-Darren** [Yang-Darren/driving-game#3]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] create a new js file and link to html
- [x] select the f1-car image element using the querySelector method
- [x] add an event listener for the keydown button
- [x] define the function for when a key is pressed
- [x] add css to rotate the car
- [x] test the see if the car turns
- [x] fix any errors
