### ISSUE TITLE
User can start their car

### ISSUE THREAD

**Issue by Yang-Darren** [Yang-Darren/driving-game#5]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x] Add X and Y positioning to data model
- [x] Add position absolute in CSS to the car image
- [x] Use the style property of the elements object to change the car's top and left box offset styles
- [x] Move car every 16 milliseconds for a smooth movement
- [x] Check functionality
- [x] Fix errors
