### ISSUE TITLE
User can stop their car

### ISSUE THREAD

**Issue by Yang-Darren** [Yang-Darren/driving-game#7]
## 💰 Motivation

If the user cannot stop their car, it goes off the page.

## 📐 Plan

Stop the car if the user presses space again.

## ✅ Task List

- [x] Add new property to data model for starting or stopping car
- [x] Add variable for clear interval later on
- [x] Add function for car speed property to change and clearing interval for car to stop
- [x] Test functionality
- [x] Fix errors
