### ISSUE TITLE
User can steer their car

### ISSUE THREAD

**Issue by Yang-Darren** [Yang-Darren/driving-game#9]
## 💰 Motivation

Our game needs MAXIMUM realism to be immersive 😂.

## 📐 Plan

Change the car's location based on which direction it is facing.

## ✅ Task List

- [x] Add function for when left arrow is pushed and car facing left, it will move to the left
- [x] Add function for when up arrow is pushed and car facing up, it will move up
- [x] Add function for when down arrow is pushed and car facing down, it will move down
- [x] Test and fix errors
